### ISSUE TITLE
Migrations of old images to new system that are published

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/docker-images#41]
- [x] bbtools/2.0.0

- [x] bcl2fastq2.17/2.0.0
- [x] bicfbase/1.1
- [x] bicfbase/2.0.0

- [x] cellranger2.1.1/2.0.0
- [x] cellranger3.0.2/2.0.0
- [x] cellranger3.1.0/2.0.0
- [x] diamond/2.0.0

- [x] fastqc/1.1
- [x] fastqc/2.0.0

- [x] java12/2.0.0
- [x] megan6/2.0.0

- [x] metagenemark/2.0.0

- [x] multiqc/1.1
- [x] multiqc/2.0.0

- [x] perl/2.0.0

- [x] perlcheckdesign/2.0.0

- [x] python3/2.0.0

- [x] spades/2.0.0
- [x] sratoolkit/1.1

- [x] sratoolkit/2.0.0

**Comment by jgesell** [comment]
All requested legacy images have been added.  At some point, I need to build updated versions of some of these to keep them up to date with the latest base image.
